// Web Push subscription management (client side).
// Subscribes this device to push, persists the subscription in Supabase
// (`push_subscriptions`), and exposes helpers to trigger pushes via the
// `send-push` edge function. Designed to fail soft — a missing edge function or
// denied permission never blocks the rest of the app.

import { supabase } from "@/integrations/supabase/client";
import { VAPID_PUBLIC_KEY } from "@/config/push";
import { ensureRegistration } from "@/lib/pwa";

export type PushState = "unsupported" | "denied" | "default" | "subscribed";

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = "=".repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, "+").replace(/_/g, "/");
  const raw = atob(base64);
  const output = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) output[i] = raw.charCodeAt(i);
  return output;
}

export function isPushSupported(): boolean {
  return (
    typeof window !== "undefined" &&
    "serviceWorker" in navigator &&
    "PushManager" in window &&
    "Notification" in window
  );
}

export async function getPushState(): Promise<PushState> {
  if (!isPushSupported()) return "unsupported";
  if (Notification.permission === "denied") return "denied";
  const reg = await ensureRegistration();
  if (!reg) return Notification.permission === "granted" ? "default" : "default";
  const sub = await reg.pushManager.getSubscription();
  if (sub && Notification.permission === "granted") return "subscribed";
  return Notification.permission === "granted" ? "default" : "default";
}

/** Subscribe THIS device to push and store it for the current user. */
export async function subscribeToPush(): Promise<{ ok: boolean; error?: string }> {
  if (!isPushSupported()) return { ok: false, error: "Este navegador no soporta notificaciones push." };

  const permission = await Notification.requestPermission();
  if (permission !== "granted") {
    return { ok: false, error: "Permiso de notificaciones denegado." };
  }

  const reg = await ensureRegistration();
  if (!reg) return { ok: false, error: "Service worker no disponible." };

  let sub: PushSubscription;
  try {
    sub = await reg.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY) as BufferSource,
    });
  } catch (err: any) {
    return { ok: false, error: err?.message || "No se pudo crear la suscripción." };
  }

  const { data: auth } = await supabase.auth.getUser();
  const userId = auth.user?.id;
  if (!userId) return { ok: false, error: "Sesión no válida." };

  const json = sub.toJSON();
  // `push_subscriptions` is created by migration 20260622000000 but may not yet be
  // in the generated Supabase types — cast until types are regenerated by Lovable.
  const db = supabase as unknown as {
    from: (t: string) => any;
  };
  const { error } = await db.from("push_subscriptions").upsert(
    {
      user_id: userId,
      endpoint: sub.endpoint,
      p256dh: json.keys?.p256dh ?? "",
      auth: json.keys?.auth ?? "",
      user_agent: navigator.userAgent.slice(0, 250),
    },
    { onConflict: "endpoint" }
  );

  if (error) return { ok: false, error: error.message };
  return { ok: true };
}

/** Remove this device's subscription. */
export async function unsubscribeFromPush(): Promise<{ ok: boolean; error?: string }> {
  const reg = await ensureRegistration();
  if (!reg) return { ok: true };
  const sub = await reg.pushManager.getSubscription();
  if (!sub) return { ok: true };
  const endpoint = sub.endpoint;
  try {
    await sub.unsubscribe();
  } catch {
    /* ignore */
  }
  await (supabase as unknown as { from: (t: string) => any })
    .from("push_subscriptions")
    .delete()
    .eq("endpoint", endpoint);
  return { ok: true };
}

/** Fire a push for an app event. Fire-and-forget; never throws to the caller. */
export async function dispatchPush(
  event: "video_delivered" | "video_status" | "editor_assigned" | "test",
  body: Record<string, unknown>
): Promise<void> {
  try {
    await supabase.functions.invoke("send-push", { body: { event, ...body } });
  } catch (err) {
    // Edge function not deployed / unreachable — degrade silently. In-app
    // notifications (DB triggers) still work; only the phone push is skipped.
    console.warn("[push] dispatch failed:", err);
  }
}

/** Send a test push to the current user's own devices (diagnostics). */
export async function sendTestPush(): Promise<{ ok: boolean; error?: string }> {
  try {
    const { data, error } = await supabase.functions.invoke("send-push", {
      body: { event: "test" },
    });
    if (error) return { ok: false, error: error.message };
    const sent = (data as any)?.sent ?? 0;
    if (sent === 0) {
      return { ok: false, error: "No hay dispositivos suscritos (o la función no encontró tu suscripción)." };
    }
    return { ok: true };
  } catch (err: any) {
    return { ok: false, error: err?.message || "La función send-push no respondió." };
  }
}
