// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-videos.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_videos_default = defineTool({
  name: "list_videos",
  title: "Listar videos",
  description: "Lista los videos del panel de Consultora DV visibles para el usuario autenticado (respeta RLS). Filtros opcionales por estado (pending/approved/rejected/in_review) y cliente.",
  inputSchema: {
    status: z.string().optional().describe("Filtrar por estado exacto del video."),
    cliente_id: z.string().uuid().optional().describe("Filtrar por ID del cliente."),
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de filas (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, cliente_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sbForUser(ctx).from("videos").select("id,title,status,platform,delivery_date,embed_url,cliente_id,rec_number,editor_name,priority,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (cliente_id) q = q.eq("cliente_id", cliente_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { videos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-scripts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_scripts_default = defineTool2({
  name: "list_scripts",
  title: "Listar guiones",
  description: "Lista los guiones (scripts) del panel visibles para el usuario autenticado. Respeta RLS.",
  inputSchema: {
    status: z2.string().optional().describe("Filtrar por estado."),
    cliente_id: z2.string().uuid().optional(),
    limit: z2.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, cliente_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sbForUser2(ctx).from("scripts").select("id,title,status,date,drive_link,cliente_id,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (status) q = q.eq("status", status);
    if (cliente_id) q = q.eq("cliente_id", cliente_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { scripts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-calendar-events.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_calendar_events_default = defineTool3({
  name: "list_calendar_events",
  title: "Listar eventos del calendario",
  description: "Lista eventos del calendario editorial en un rango de fechas (YYYY-MM-DD). Respeta RLS.",
  inputSchema: {
    from: z3.string().optional().describe("Fecha inicial YYYY-MM-DD (inclusive)."),
    to: z3.string().optional().describe("Fecha final YYYY-MM-DD (inclusive)."),
    cliente_id: z3.string().uuid().optional(),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, cliente_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sbForUser3(ctx).from("calendar_events").select("id,title,date,time,platform,content_type,cliente_id,video_id").order("date", { ascending: true }).limit(limit ?? 50);
    if (from) q = q.gte("date", from);
    if (to) q = q.lte("date", to);
    if (cliente_id) q = q.eq("cliente_id", cliente_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-documents.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function sbForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_documents_default = defineTool4({
  name: "list_documents",
  title: "Listar documentos",
  description: "Lista los documentos del panel visibles para el usuario autenticado. Respeta RLS.",
  inputSchema: {
    cliente_id: z4.string().uuid().optional(),
    type: z4.string().optional().describe("Filtrar por tipo (contrato, brief, etc.)."),
    limit: z4.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ cliente_id, type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    let q = sbForUser4(ctx).from("documents").select("id,name,type,date,drive_link,file_url,cliente_id,updated_at").order("updated_at", { ascending: false }).limit(limit ?? 25);
    if (cliente_id) q = q.eq("cliente_id", cliente_id);
    if (type) q = q.eq("type", type);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.103.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
function sbForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Mi perfil",
  description: "Devuelve el perfil, rol y estado de aprobaci\xF3n del usuario autenticado en el panel de Consultora DV.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const sb = sbForUser5(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error: pErr }, { data: roles, error: rErr }] = await Promise.all([
      sb.from("profiles").select("display_name,email,business,approval_status,phone,bio").eq("user_id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId)
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (rErr) return { content: [{ type: "text", text: rErr.message }], isError: true };
    const result = { user_id: userId, email: ctx.getUserEmail(), profile, roles: (roles ?? []).map((r) => r.role) };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wczkjsqcqbvqkmbyrzrr";
var mcp_default = defineMcp({
  name: "dv-client-hub",
  title: "Consultora DV \u2014 Panel de Clientes",
  version: "0.1.0",
  instructions: "Herramientas del panel privado de Consultora DV (Dante Vega). Cada llamada se ejecuta como el usuario autenticado; RLS de Lovable Cloud filtra los datos que el usuario puede ver. Usa list_videos, list_scripts, list_calendar_events, list_documents y get_my_profile para consultar el trabajo del cliente conectado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_profile_default, list_videos_default, list_scripts_default, list_calendar_events_default, list_documents_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
